### ISSUE TITLE
User rights

### ISSUE THREAD

**Issue by pieterdp** [PACKED-vzw/resolver#14]
User rights must be supported.

**Comment by bert-packed** [comment]
Discussed the need for user rights halfway between v1. and v2.
We still have the opinion that there is no need for functionality managing different levels of user access.
Basically there is only on user type, being the data manager. So you are data manager and you have access to the resolver, or you don't. 
Since we avoid adding other responsibilities to the use of the resolver, we do not expect their will be need for user rights in the future.
