### ISSUE TITLE
Importmodule herdenken

### ISSUE THREAD

**Issue by pieterdp** [PACKED-vzw/resolver#15]
Complexere importbestanden ondersteunen (fail, update etc.)

**Comment by bert-packed** [comment]
Discusion halfway between v1.0 and v2.0

We changed the import mechanism from import/export the entire dataset to an update mechanism: the system checks for the PID: if present it update the entity, if not present it creates a new entity. 

This should solve the problems with uploading large dataset and facilitates automated updates of single entities via the api.

IS this enough for v2.0 or are there other related issues that require rethinking the import module?

**Comment by netsensei** [comment]
The incremental updates help me to import a larger dataset.  However, to do that:
- I need to split out the CSV file in several smaller files, guesstimating which size the Resolver will accept.
- I need to manually import each file in the resolver
- I need to check the "stats" page to know if all the number of rows in the CSV matches the number of rows which were imported.

If I have made an error somewhere in the import file (ie. accidentally denoted a representation URL as a data URL or such) I risk overwriting data in the resolver. The resolver won't throw me an error or a notice. The only indication that something went wrong: the numbers in the resolver "stats" page and the CSV file don't match up. In this case, I need to:
- Go back in Refine, and find the offending rows and fix them (using the 'transform' action or manually with text filters & facets).
- Export the entire file again from Refine
- Split the large file in new subfiles again
- Import those files again one by one. (There are no guarantees that I my transform operation didn't corrupt the data I had already imported)

So, there's a lot of manual actions I need to take to prepare the data before and during importing a batch of data.

Now, imagine that 6 months down the road, the inventory numbers/PID's in the collection registration systems have changed (standard maintenance operations like cleaning up, etc.) That means going through most of the motions I described above again.

Splitting up a larger import file adds extra time consuming tasks. It's shifting the burden to the user / data publisher in order to avoid fixing a technical shortcoming.

**Comment by nvgeele** [comment]
For what it's worth, I have created a script in the root directory of the project, `import_csv.py`, that can be used to import (large) csv files via the command line. If necessary this script can be used to configure cron jobs, although that's a rather hackish solution.
