### ISSUE TITLE
Large dataset causes sluggish overview UI

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#7]
_Description_

The overview page takes some time to load when a large set (ie 2200 objects) was imported;

_Steps to reproduce_
1. Create a large import file via Open Refine
2. Navigate to the import interface
3. Import the file in the resolver

_Actual behavior_

Slow loading of the page. You have to wait before the pagination pager becomes active/clickable.

_Expected behaviour_

A usable interface;

_Proposed resolution_

TBD

**Comment by nvgeele** [comment]
This issue is caused by the way we originally chose to render the overview page. Currently, all objects in the system are put in a table on the page and are automagically paginated using JS. Obviously, more objects in the system means greater loading times and more memory usage on the client.

The obvious solution is loading the data dynamically or using static pagination.

**Comment by netsensei** [comment]
My vote would go to dynamic pagination. See this screencast I made some time ago: https://www.youtube.com/watch?v=dJhnyjXLJds ;-)
